repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest commit hash or tag from the repo
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest commit hash or tag from the repo
    hooks:
      - id: flake8

#  - repo: https://github.com/psf/black
#    rev: 24.4.0  # Use the latest commit hash or tag from the repo
#    hooks:
#      - id: black
#        args: ["--safe", "--line-length=88"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest commit hash or tag from the repo
    hooks:
      - id: isort
        args: ["--profile", "black"]
