services:
  database:
    container_name: parsing_challenge_database
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - parsing_challenge_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  parser:
    container_name: parsing_challenge
    image: sergei1m/parsing_challenge:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database

volumes:
  parsing_challenge_db:
